# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-18 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('authors_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='Books.Authors')),
                ('bookId', models.CharField(max_length=30)),
                ('bookName', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('Books.authors', models.Model),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.AlterField(
            model_name='authors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 55, 52, 972715)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 55, 52, 972760)),
        ),
    ]
